-- 切換使用資料庫
USE RentalManagementPlatformSQL;
GO

-- 先刪除索引 (若存在)
DROP INDEX IF EXISTS [POSTS_index_0] ON [POSTS];
GO

-- 刪除所有資料表
DROP TABLE IF EXISTS [MONGODB];
DROP TABLE IF EXISTS [EMAIL_VERIFICATIONS];
DROP TABLE IF EXISTS [ANOMALY_DETECTION_LOG];
DROP TABLE IF EXISTS [ANOMALY_RULE];
DROP TABLE IF EXISTS [USER_FAVORITE_REPORT];
DROP TABLE IF EXISTS [POSTS_CATEGORIES];
DROP TABLE IF EXISTS [CATEGORIES];
DROP TABLE IF EXISTS [POSTS];
DROP TABLE IF EXISTS [MESSAGE];
DROP TABLE IF EXISTS [SUPPORT_TICKETS];
DROP TABLE IF EXISTS [FAQ_FEEDBACK];
DROP TABLE IF EXISTS [FAQ_ARTICLES];
DROP TABLE IF EXISTS [FAQ_CATEGORIES];
DROP TABLE IF EXISTS [POINT_LEDGER];
DROP TABLE IF EXISTS [POINT_RULE];
DROP TABLE IF EXISTS [SUBSCRIPTION_BILLING_LOG];
DROP TABLE IF EXISTS [HOST_SUBSCRIPTION];
DROP TABLE IF EXISTS [SUBSCRIPTION_PLAN];
DROP TABLE IF EXISTS [HOST_PAYOUT_ITEM];
DROP TABLE IF EXISTS [HOST_PAYOUT];
DROP TABLE IF EXISTS [USER_ROLES];
DROP TABLE IF EXISTS [ROLE_PERMISSIONS];
DROP TABLE IF EXISTS [PERMISSIONS];
DROP TABLE IF EXISTS [ROLES];
DROP TABLE IF EXISTS [ROOM_PHOTO];
DROP TABLE IF EXISTS [ROOM_LIST];
DROP TABLE IF EXISTS [REVIEW];
DROP TABLE IF EXISTS [PAYMENT_TRANSACTION];
DROP TABLE IF EXISTS [PAYMENT];
DROP TABLE IF EXISTS [COUPON_DISTRICT];
DROP TABLE IF EXISTS [COUPON_GUEST];
DROP TABLE IF EXISTS [COUPON];
DROP TABLE IF EXISTS [CITY];
DROP TABLE IF EXISTS [DISTRICT];
DROP TABLE IF EXISTS [BOOKING_GUEST];
DROP TABLE IF EXISTS [BOOKING];
DROP TABLE IF EXISTS [USER];
DROP TABLE IF EXISTS [ADDRESS];
DROP TABLE IF EXISTS [PASSWORD_RESET_TOKENS];
DROP TABLE IF EXISTS [REFRESH_TOKENS];
GO
