-- 切換使用資料庫
USE RentalManagementPlatformSQL;

ALTER TABLE [PASSWORD_RESET_TOKENS] DROP CONSTRAINT FK_PASSWORD_RESET_TOKENS_user_id_USER_user_id;
GO

ALTER TABLE [ADDRESS] DROP CONSTRAINT FK_ADDRESS_district_id_DISTRICT_district_id;
GO

ALTER TABLE [BOOKING] DROP CONSTRAINT FK_BOOKING_coupon_id_COUPON_coupon_id;
GO

ALTER TABLE [BOOKING] DROP CONSTRAINT FK_BOOKING_guest_id_USER_user_id;
GO

ALTER TABLE [BOOKING] DROP CONSTRAINT FK_BOOKING_room_id_ROOM_LIST_room_id;
GO

ALTER TABLE [BOOKING_GUEST] DROP CONSTRAINT FK_BOOKING_GUEST_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [COUPON_GUEST] DROP CONSTRAINT FK_COUPON_GUEST_coupon_id_COUPON_coupon_id;
GO

ALTER TABLE [COUPON_GUEST] DROP CONSTRAINT FK_COUPON_GUEST_guest_id_USER_user_id;
GO

ALTER TABLE [COUPON_DISTRICT] DROP CONSTRAINT FK_COUPON_DISTRICT_coupon_id_COUPON_coupon_id;
GO

ALTER TABLE [COUPON_DISTRICT] DROP CONSTRAINT FK_COUPON_DISTRICT_district_id_DISTRICT_district_id;
GO

ALTER TABLE [DISTRICT] DROP CONSTRAINT FK_DISTRICT_city_id_CITY_city_id;
GO

ALTER TABLE [PAYMENT] DROP CONSTRAINT FK_PAYMENT_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [PAYMENT_TRANSACTION] DROP CONSTRAINT FK_PAYMENT_TRANSACTION_payment_id_PAYMENT_payment_id;
GO

ALTER TABLE [REVIEW] DROP CONSTRAINT FK_REVIEW_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [REVIEW] DROP CONSTRAINT FK_REVIEW_host_id_USER_user_id;
GO

ALTER TABLE [REVIEW] DROP CONSTRAINT FK_REVIEW_reviewer_id_USER_user_id;
GO

ALTER TABLE [REVIEW] DROP CONSTRAINT FK_REVIEW_room_id_ROOM_LIST_room_id;
GO

ALTER TABLE [ROOM_LIST] DROP CONSTRAINT FK_ROOM_LIST_address_id_ADDRESS_address_id;
GO

ALTER TABLE [ROOM_LIST] DROP CONSTRAINT FK_ROOM_LIST_host_id_USER_user_id;
GO

ALTER TABLE [ROOM_PHOTO] DROP CONSTRAINT FK_ROOM_PHOTO_room_id_ROOM_LIST_room_id;
GO

ALTER TABLE [ROLE_PERMISSIONS] DROP CONSTRAINT FK_ROLE_PERMISSIONS_role_id_ROLES_role_id;
GO

ALTER TABLE [ROLE_PERMISSIONS] DROP CONSTRAINT FK_ROLE_PERMISSIONS_permission_id_PERMISSIONS_permission_id;
GO

ALTER TABLE [USER_ROLES] DROP CONSTRAINT FK_USER_ROLES_user_id_USER_user_id;
GO

ALTER TABLE [USER_ROLES] DROP CONSTRAINT FK_USER_ROLES_role_id_ROLES_role_id;
GO

ALTER TABLE [HOST_PAYOUT] DROP CONSTRAINT FK_HOST_PAYOUT_host_id_USER_user_id;
GO

ALTER TABLE [HOST_PAYOUT_ITEM] DROP CONSTRAINT FK_HOST_PAYOUT_ITEM_payout_id_HOST_PAYOUT_payout_id;
GO

ALTER TABLE [HOST_PAYOUT_ITEM] DROP CONSTRAINT FK_HOST_PAYOUT_ITEM_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [HOST_SUBSCRIPTION] DROP CONSTRAINT FK_HOST_SUBSCRIPTION_host_id_USER_user_id;
GO

ALTER TABLE [HOST_SUBSCRIPTION] DROP CONSTRAINT FK_HOST_SUBSCRIPTION_plan_id_SUBSCRIPTION_PLAN_plan_id;
GO

ALTER TABLE [SUBSCRIPTION_BILLING_LOG] DROP CONSTRAINT FK_SUBSCRIPTION_BILLING_LOG_host_sub_id_HOST_SUBSCRIPTION_host_sub_id;
GO

ALTER TABLE [POINT_LEDGER] DROP CONSTRAINT FK_POINT_LEDGER_guest_id_USER_user_id;
GO

ALTER TABLE [POINT_LEDGER] DROP CONSTRAINT FK_POINT_LEDGER_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [FAQ_CATEGORIES] DROP CONSTRAINT FK_FAQ_CATEGORIES_parent_id_FAQ_CATEGORIES_faq_categories_id;
GO

ALTER TABLE [FAQ_ARTICLES] DROP CONSTRAINT FK_FAQ_ARTICLES_category_id_FAQ_CATEGORIES_faq_categories_id;
GO

ALTER TABLE [FAQ_ARTICLES] DROP CONSTRAINT FK_FAQ_ARTICLES_author_id_USER_user_id;
GO

ALTER TABLE [FAQ_FEEDBACK] DROP CONSTRAINT FK_FAQ_FEEDBACK_article_id_FAQ_ARTICLES_faq_articles_id;
GO

ALTER TABLE [SUPPORT_TICKETS] DROP CONSTRAINT FK_SUPPORT_TICKETS_related_feedback_id_FAQ_ARTICLES_faq_articles_id;
GO

ALTER TABLE [SUPPORT_TICKETS] DROP CONSTRAINT FK_SUPPORT_TICKETS_assigned_staff_id_USER_user_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_ticket_id_SUPPORT_TICKETS_support_tickets_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_booking_id_BOOKING_booking_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_receiver_id_USER_user_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_room_id_ROOM_LIST_room_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_sender_id_USER_user_id;
GO

ALTER TABLE [MESSAGE] DROP CONSTRAINT FK_MESSAGE_faq_id_FAQ_ARTICLES_faq_articles_id;
GO

ALTER TABLE [POSTS_CATEGORIES] DROP CONSTRAINT FK_POSTS_CATEGORIES_posts_id_POSTS_posts_id;
GO

ALTER TABLE [POSTS_CATEGORIES] DROP CONSTRAINT FK_POSTS_CATEGORIES_categories_id_CATEGORIES_categories_id;
GO

ALTER TABLE [POSTS] DROP CONSTRAINT FK_POSTS_user_id_USER_user_id;
GO

ALTER TABLE [POSTS] DROP CONSTRAINT FK_POSTS_region_id_DISTRICT_district_id;
GO

ALTER TABLE [USER_FAVORITE_REPORT] DROP CONSTRAINT FK_USER_FAVORITE_REPORT_user_id_USER_user_id;
GO

ALTER TABLE [ANOMALY_DETECTION_LOG] DROP CONSTRAINT FK_ANOMALY_DETECTION_LOG_rule_id_ANOMALY_RULE_rule_id;
GO

ALTER TABLE [MONGODB] DROP CONSTRAINT FK_MONGODB_ListingId_ROOM_LIST_room_id;
GO
