worker_processes auto;
events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  # 預設擋掉未設定的 Host
  server {
    listen 80;
    server_name _;
    return 444;
  }

  # 測試 httpbin 反代
  server {
    listen 80;
    server_name httpbin.local;

    location / {
      proxy_pass http://httpbin:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
