-- Drop FK constraints for Subscription module
ALTER TABLE HOST_SUBSCRIPTION
DROP CONSTRAINT FK_HOST_SUBSCRIPTION_PLAN;

ALTER TABLE SUBSCRIPTION_BILLING_LOG
DROP CONSTRAINT FK_SUBSCRIPTION_BILLING_LOG_HOST_SUB;
