-- Add FK constraints for Subscription module
ALTER TABLE HOST_SUBSCRIPTION
ADD CONSTRAINT FK_HOST_SUBSCRIPTION_PLAN FOREIGN KEY (plan_id) REFERENCES SUBSCRIPTION_PLAN(plan_id);

ALTER TABLE SUBSCRIPTION_BILLING_LOG
ADD CONSTRAINT FK_SUBSCRIPTION_BILLING_LOG_HOST_SUB FOREIGN KEY (host_sub_id) REFERENCES HOST_SUBSCRIPTION(host_sub_id);
