ALTER TABLE PAYMENT DROP CONSTRAINT FK_PAYMENT_BOOKING;
ALTER TABLE PAYMENT_TRANSACTION DROP CONSTRAINT FK_PAYMENT_TRANSACTION_PAYMENT;
ALTER TABLE HOST_PAYOUT_ITEM DROP CONSTRAINT FK_PAYOUT_ITEM_PAYOUT;
ALTER TABLE HOST_PAYOUT_ITEM DROP CONSTRAINT FK_PAYOUT_ITEM_BOOKING;
