-- PAYMENT.booking_id → BOOKING.booking_id
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_BOOKING
FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id);

-- PAYMENT_TRANSACTION.payment_id → PAYMENT.payment_id
ALTER TABLE PAYMENT_TRANSACTION
ADD CONSTRAINT FK_PAYMENT_TRANSACTION_PAYMENT
FOREIGN KEY (payment_id) REFERENCES PAYMENT(payment_id);

-- HOST_PAYOUT_ITEM.payout_id → HOST_PAYOUT.payout_id
ALTER TABLE HOST_PAYOUT_ITEM
ADD CONSTRAINT FK_PAYOUT_ITEM_PAYOUT
FOREIGN KEY (payout_id) REFERENCES HOST_PAYOUT(payout_id);

-- HOST_PAYOUT_ITEM.booking_id → BOOKING.booking_id
ALTER TABLE HOST_PAYOUT_ITEM
ADD CONSTRAINT FK_PAYOUT_ITEM_BOOKING
FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id);
