// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RentalManagementPlatformMVC.Models;

[Table("BOOKING_GUEST")]
public partial class BookingGuest
{
    [Key]
    [Column("booking_guest_id")]
    public int BookingGuestId { get; set; }

    [Column("booking_id")]
    public int BookingId { get; set; }

    [Required]
    [Column("guest_name")]
    [StringLength(100)]
    public string GuestName { get; set; }

    [Required]
    [Column("guest_id_number")]
    [StringLength(20)]
    public string GuestIdNumber { get; set; }
}