// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RentalManagementPlatformMVC.Models;

[Table("BOOKING")]
[Index("OrderNumber", Name = "IXU_BOOKING_order_number", IsUnique = true)]
public partial class Booking
{
    [Key]
    [Column("booking_id")]
    public int BookingId { get; set; }

    [Column("coupon_id")]
    public int? CouponId { get; set; }

    [Column("guest_id")]
    public int? GuestId { get; set; }

    [Column("room_id")]
    public int? RoomId { get; set; }

    [Column("order_number")]
    [StringLength(512)]
    public string OrderNumber { get; set; }

    [Column("check_in")]
    public DateTime? CheckIn { get; set; }

    [Column("check_out")]
    public DateTime? CheckOut { get; set; }

    [Column("total_price", TypeName = "decimal(18, 2)")]
    public decimal? TotalPrice { get; set; }

    [Column("commission_rate_snapshot", TypeName = "decimal(5, 2)")]
    public decimal? CommissionRateSnapshot { get; set; }

    [Column("points_earned")]
    public int? PointsEarned { get; set; }

    [Column("points_redeemed")]
    public int? PointsRedeemed { get; set; }

    [Column("status")]
    [StringLength(512)]
    public string Status { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    // 導覽屬性：一個訂單對應多個房客
    public virtual ICollection<BookingGuest> BookingGuests { get; set; } = new List<BookingGuest>();
}