// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RentalManagementPlatformMVC.Models;

public partial class BookingDbContext : DbContext
{
    public BookingDbContext(DbContextOptions<BookingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingGuest> BookingGuests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__BOOKING__5DE3A5B109C63A63");

            entity.Property(e => e.BookingId).ValueGeneratedNever();
        });

        modelBuilder.Entity<BookingGuest>(entity =>
        {
            entity.HasKey(e => e.BookingGuestId).HasName("PK__BOOKING___A6D88E88DE67AC8D");

            entity.Property(e => e.BookingGuestId).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}